name: 'Terraform CI/CD'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: "us-east-2"
  TF_WORKSPACE: "aws-vpc-basic"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AWS/aws-vpc-basic

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.13.3

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        rm -f .terraform/terraform.tfstate
        terraform init -reconfigure \
          -backend=true \
          -backend-config="bucket=terraform-state-pavankiran222" \
          -backend-config="key=aws-vpc-basic/terraform.tfstate" \
          -backend-config="region=us-east-2" \
          -backend-config="dynamodb_table=terraform-state-lock"
        terraform state pull

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Create tfvars file
      run: |
        echo 'ssh_public_key = "${{ secrets.SSH_PUBLIC_KEY }}"' > terraform.tfvars
        cat terraform.tfvars

    - name: Terraform Plan
      if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy'
      run: |
        terraform plan \
          -no-color \
          -input=false \
          -refresh=true
      
    - name: Terraform Apply
      if: github.event.inputs.action == 'apply'
      run: terraform apply -auto-approve -input=false
      
    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform destroy -auto-approve -input=false